const types = {
    SET_THEME: 'SET_THEME',
    SET_FBDATOS: 'SET_FBDATOS',
    SET_LOADING: 'SET_LOADING',
    SET_TIMESTART: 'SET_TIMESTART',
    SET_TIMEEND: 'SET_TIMEEND',
    SET_TIMESTARTPAST: 'SET_TIMESTARTPAST',
    SET_TIMEENDPAST: 'SET_TIMEENDPAST',
  };
  
  export default types;
  